### ISSUE TITLE
Vertaispalaute 2

### ISSUE THREAD

**Issue by pllk** [mojord/billions#2]
Käyttökokemus

* Sovelluksen idea on hyvä ja siitä tulee hyvä sovellus, kun loput toiminnot valmistuvat.

* Lomakkeissa näyttää oudolta, että kentät ovat vierekkäin vaakasuunnassa.

* En ymmärtänyt, mikä merkitys on salkun luomisella, kun niitä voi olla vain yksi. Voisiko käyttäjällä olla heti salkku, kun luo uuden käyttäjän?

* Osakkeiden löytäminen on tällä hetkellä hieman vaikeaa, mutta onnistuin siinä kuitenkin.

* Kun ostan osaketta, olisi hyödyllistä nähdä kokonaishinta (ei vain määrä ja yhden osakkeen hinta).

* Kun yritin myydä osaketta (jota minulla ei ollut), tuli sivu Internal Server Error.

Tekninen toteutus

* Gitin commit-viestit eivät ole hyviä (esim. "the rest of the app"). Viestin tulisi kertoa, minkä muutoksen commit aiheuttaa sovellukseen.

* Pythonissa on valmiina moduuli `csv`, joka voisi sopia omaa toteutusta paremmin csv-tiedoston lukemiseen.

* Kysely muotoa `SELECT *` ei ole hyvä vaan kannattaa aina ilmoittaa haettavat sarakkeet.

* Tiedostossa `market_repository.py` rivit 27–30 voisi korvata yhdellä `return`-rivillä.

**Comment by mojord** [comment]
Yllä olevaan kannattaa tutustua täydellisenä esimerkkinä siitä, miten palautetta ei tule antaa. HUOM! kyseessä ei ole oikea vertaisarvio, vaan jotain muuta.

Ensinnäkin ei ole luettu README:sta edes kappaletta sovelluksen tilasta tällä hetkellä. Käyttäjällä voi olla monta salkkua, mutta vain yksi kerrallaan. Osa virheilmoituksista on tosiaan toteuttamatta. Toiseksi keskitytään kuvailemaan työtä negatiivisin adjektiivein: outoa, vaikeaa, ei hyviä. Jokainen kelvollinen vertaisarvioijahan tietää, ettei tällaisesta ole mitään hyötyä, vaan kyse lienee lähinnä tarpeesta nälviä. Eli "osakkeiden löytäminen oli vaikeaa, koska ... "olisi hyödyllisen kommentin aloitus. Ja kaikki huono, outo tms. adjektiivit kannattaa korvata rakentavilla ilmaisuilla, koska haukkumisesta ei ole mitään iloa. Vastaavasti, kun kommentoija ei selitä, miksi spesifin csv-alkutoimen toteuttamiseen csv-moduuli sopisi paremmin, syntyy lähinnä mielikuva, että kommentoija haluaa vain esitellä tietämystään tällaisen moduulin olemassaolosta, vaikka siitä ei ole tekijälle mitään hyötyä.
Eli hyvää vertaisarviota antaessa kannattaa aina harjoittaa itsekritiikkiä: Tutustuinko arvioitavaan työhön huolellisesti? Nälvinkö tekijää turhilla kielteisillä adjektiiveilla? Keskitynkö olennaiseen? Ovatko jotkut kommenttini vain oman erinomaisuuteni esille tuomista? Onko kommenteista hyötyä?

Tällä kysymyssetillä pääsee pitkälle vertaisarvioijana. Eikä siitä ole hyötyä vain hienon vertaisarvion saajalle, vaan myös itselle, koska samalla oppii hyvän ja rakentavan tavan arvioida myös omaa työtään. Kiitän "älä tee näin" -mallin antajaa yhteistyöstä.
